kind: pipeline
name: build_linux_amd64

clone:
  depth: 50

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags

  - name: binary
    image: golang:1.15
    pull: true
    commands:
      - make build_linux_amd64

  - name: publish
    image: plugins/docker:17.12
    settings:
      repo: dan-kirberger/djerk-djym-api
      auto_tag: true
      dockerfile: Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event: push
      branch: master