kind: pipeline
name: build


workspace:
  base: /go
  path: src/github.com/dan-kirberger/djerk-djym-api

services:
  - name: mongo
    image: mongo:4.1

steps:
  - name: test
    image: golang:1.11
    pull: true
    environment:
       MONGO_URI: "mongodb://mongo:27017"
    commands:
      - go get github.com/mongodb/mongo-go-driver/...
      - go test -v

#  - name: publish
#    image: plugins/docker:17.12
#    settings:
#      repo: dankirberger/djerk-djym-api
#      auto_tag: true
#      dockerfile: Dockerfile
#      username:
#        from_secret: docker_username
#      password:
#        from_secret: docker_password
#    when:
#      event: push
#      branch: master