kind: pipeline
name: build_linux_amd64

steps:
  - name: binary
    image: golang:1.11
    pull: true
    commands:
      - make build_linux_amd64

  - name: publish
    image: plugins/docker:17.12
    settings:
      repo: dankirberger/djerk-djym-api
      auto_tag: true
      dockerfile: Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event: push
      branch: master